apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sf-exporter-chart.fullname" . }}-secrets
  labels:
    app: {{ template "sf-exporter-chart.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  s3_access_key:  {{ .Values.sfexporter.s3AccessKey | b64enc | quote }}
  s3_secret_key:  {{ .Values.sfexporter.s3SecretKey | b64enc | quote }}
