apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-analytics-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sf-analytics-chart.name" . }}
    helm.sh/chart: {{ include "sf-analytics-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sf-analytics-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sf-analytics-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.fullnameOverride }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: COS_ENDPOINT
            value: "{{ .Values.sfanalytics.cosEndpoint }}"
          - name: COS_PORT
            value: "{{ .Values.sfanalytics.cosPort }}"
          - name: INTERVAL
            value: "{{ .Values.sfanalytics.interval }}"
          - name: TIMEOUT
            value: "{{ .Values.sfanalytics.timeout }}"
          - name: COS_BUCKET
            value: "{{ .Values.sfanalytics.cosBucket }}"
          - name: COS_LOCATION
            value: "{{ .Values.sfanalytics.cosLocation }}"
          - name: AE_ENDPOINT
            value: "{{ .Values.sfanalytics.aeEndpoint }}"
          - name: AE_UPLOAD
            value: "{{ .Values.sfanalytics.aeUpload }}"
          - name: IAM_ENDPOINT
            value: "{{ .Values.sfanalytics.iamEndpoint }}"
          - name: DEBUG
            value: "{{ .Values.sfanalytics.debug }}"
          - name: AE_DRIVER_MEM
            value: "{{ .Values.sfanalytics.aeDriverMem }}"
          - name: AE_EXECUTOR_MEM
            value: "{{ .Values.sfanalytics.aeExecutorMem }}"
          volumeMounts:
            - mountPath: "/run/secrets/k8s"
              name: secrets
              subpath: k8s
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.image.secretName }}
      {{- if ne .Values.image.secretName ""}}
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      {{- end }}
    {{- end }}
      volumes:
      - name: secrets
        secret:
          secretName: {{ template "sf-analytics-chart.fullname" . }}-secrets
          items:
          - key: iam_api_key
            path: "iam_api_key"
          - key: ae_user
            path: "ae_user"
          - key: ae_pwd
            path: "ae_pwd"
          - key: kp_instance_id
            path: "kp_instance_id"


