apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysflow-operator
imagePullSecrets:
- name: default-icr-io
- name: default-us-icr-io
- name: default-uk-icr-io
- name: default-de-icr-io
- name: default-au-icr-io
- name: default-jp-icr-io
- name: default-dockercfg-47rxf
