kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: sysflow-scc
priority: 11
requiredDropCapabilities: []
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowedCapabilities:
- SYS_ADMIN
- SYS_RESOURCE
defaultAddCapabilities:
- SYS_ADMIN
- SYS_RESOURCE
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- sysflow-serviceaccount
volumes:
- configMap
- emptyDir
- hostPath
- persistentVolumeClaim
- secret
