apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sf-exporter-chart.fullname" . }}-secrets
  labels:
    app: {{ template "sf-exporter-chart.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cos_access_key:  {{ .Values.sfexporter.cosAccessKey | b64enc | quote }}
  cos_secret_key:  {{ .Values.sfexporter.cosSecretKey | b64enc | quote }}
